# Generated by Django 2.1.3 on 2019-02-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gtdb2', '0013_auto_20190227_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChelataseCof',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('gtdb2.cof',),
        ),
        migrations.CreateModel(
            name='ChelataseFeat',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('gtdb2.feat',),
        ),
        migrations.CreateModel(
            name='ChelataseFshift',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('gtdb2.fshift',),
        ),
        migrations.CreateModel(
            name='ChelataseOrg',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('gtdb2.org',),
        ),
        migrations.CreateModel(
            name='ChelataseSeq',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('gtdb2.seq',),
        ),
    ]
