version: '3'
# http://pawamoy.github.io/2018/02/01/docker-compose-django-postgres-nginx.html
# https://testdriven.io/blog/dockerizing-flask-with-postgres-gunicorn-and-nginx/
services:
    django:
        build: ./django
        command:  gunicorn --bind :8000 mysite.wsgi:application
        environment:
            - MYSQL_HOST=db
            - MYSQL_PORT=3306
            - MODE=PROD
        env_file:
            - production.env
        expose:
            - 8000
        ports:
            - 8000:8000

    db:
        image: mysql:8.0
        command:  --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        env_file:
            - production.env
        expose:
            - 3306

    app:
        build:
            context: ./
            args:
                - VUE_APP_API_BASE_URL=api
        environment:
            - VUE_APP_API_BASE_URL=api
        ports:
            - 80:80
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - django
