version: '3'

services:
    django:
        build: ./django
        command: python3 manage.py runserver 0.0.0.0:8000
        environment:
            - MYSQL_HOST=db
            - MYSQL_PORT=3306
            - MODE=PROD
        env_file:
            - production.env
        ports:
            - 8000:8000

    db:
        image: mysql:latest
        command:  --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
        env_file:
            - production.env
        ports:
          - 3307:3306

