# Generated by Django 2.1.3 on 2018-11-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtdb2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='seq',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
