# Generated by Django 2.1.3 on 2018-12-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtdb2', '0002_auto_20181227_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cof',
            name='descr',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cof',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fshift',
            name='descr',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fshift',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='org',
            name='descr',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seq',
            name='descr',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
