# Generated by Django 2.1.3 on 2018-11-29 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtdb2', '0002_auto_20181128_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userparam',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserParam',
        ),
    ]
