# Generated by Django 2.1.3 on 2018-11-29 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtdb2', '0003_auto_20181129_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgparam',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtdb2.Org'),
        ),
    ]
