# Generated by Django 2.1.3 on 2018-12-03 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtdb2', '0004_auto_20181129_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgparam',
            old_name='org',
            new_name='parent',
        ),
    ]
