# Generated by Django 2.1.3 on 2018-12-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtdb2', '0005_feat_fshift_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='cof',
            name='feat_set',
            field=models.ManyToManyField(db_table='cof_feats', to='gtdb2.Feat'),
        ),
    ]
