# Generated by Django 2.1.3 on 2018-12-03 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtdb2', '0005_auto_20181203_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seqparam',
            old_name='seq',
            new_name='parent',
        ),
    ]
