# Generated by Django 2.1.3 on 2018-12-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtdb2', '0007_fshift_fshiftparam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seq',
            name='ext_id',
        ),
    ]
