# Generated by Django 2.1.3 on 2018-12-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtdb2', '0008_remove_seq_ext_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fshift',
            name='origin',
        ),
        migrations.AddField(
            model_name='fshift',
            name='len',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fshift',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
