# Generated by Django 2.1.3 on 2019-01-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtdb2', '0009_auto_20190116_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feat',
            name='origin',
            field=models.CharField(choices=[('gbk_annotation', 'GenBank annotation'), ('genetack', 'GeneTackDB')], max_length=255),
        ),
    ]
