# Generated by Django 2.1.3 on 2018-12-11 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtdb2', '0009_auto_20181211_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fshift',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='org',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='seq',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
