# Generated by Django 2.1.3 on 2018-12-12 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtdb2', '0011_auto_20181211_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fshiftparam',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtdb2.Fshift'),
        ),
    ]
