# Generated by Django 2.1.3 on 2018-12-12 20:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gtdb2', '0012_auto_20181212_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('descr', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('type', models.CharField(max_length=255)),
                ('fshift_set', models.ManyToManyField(db_table='cof_fshifts', to='gtdb2.Fshift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtdb2.User')),
            ],
            options={
                'db_table': 'cofs',
            },
        ),
        migrations.CreateModel(
            name='CofParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('num', models.FloatField(blank=True, default=None, null=True)),
                ('data', models.TextField(blank=True, default=None, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtdb2.Cof')),
            ],
            options={
                'db_table': 'cof_params',
            },
        ),
        migrations.AlterField(
            model_name='fshiftparam',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtdb2.Fshift'),
        ),
    ]
