# Generated by Django 2.1.3 on 2018-12-18 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtdb2', '0014_auto_20181218_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='fshift',
            name='seed',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cof',
            name='fshift_set',
            field=models.ManyToManyField(db_table='cof_fshifts', to='gtdb2.Fshift'),
        ),
        migrations.AlterField(
            model_name='fshiftparam',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtdb2.Fshift'),
        ),
    ]
