# Generated by Django 2.2.4 on 2020-06-13 21:18

from django.db import migrations

from chelatase_db.models import ChelataseFshift


def add_poly_a_to_minus1_fshifts(apps, schema_editor):
    fshifts = ChelataseFshift.objects.filter(len=-1,
        feat__param_set__name="chel_subunit").all()
    print(len(fshifts))
    for fshift in fshifts:
        fshift._make_poly_a_slippery_site()


class Migration(migrations.Migration):

    dependencies = [
        ("chelatase_db", "0001_initial"),
    ]

    operations = [migrations.RunPython(add_poly_a_to_minus1_fshifts)]
