# Generated by Django 2.2.4 on 2020-06-14 21:29

from django.db import migrations

from chelatase_db.models import ChelataseFshift

try:
    from tqdm.auto import tqdm
except Exception as e:
    tqdm = list


def add_signal_ss_after_slippery_site(apps, schema_editor):
    fshifts = ChelataseFshift.objects.filter(
        len=-1, feat__param_set__name="chel_subunit", param_set__name="poly_a_start",
    ).all()
    for fshift in tqdm(fshifts):
        fshift._make_signal_secondary_structure()


class Migration(migrations.Migration):

    dependencies = [
        ("chelatase_db", "0002_add_poly_a"),
    ]

    operations = [migrations.RunPython(add_signal_ss_after_slippery_site)]
