# Generated by Django 2.1.3 on 2018-12-29 16:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gtdb2', '0003_auto_20181227_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('descr', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('type', models.CharField(max_length=255)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('strand', models.IntegerField()),
                ('seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtdb2.Seq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtdb2.User')),
            ],
            options={
                'db_table': 'feats',
            },
        ),
        migrations.CreateModel(
            name='FeatParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('num', models.FloatField(blank=True, default=None, null=True)),
                ('data', models.TextField(blank=True, default=None, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_set', to='gtdb2.Feat')),
            ],
            options={
                'db_table': 'feat_params',
            },
        ),
    ]
