# Generated by Django 2.1.3 on 2018-12-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtdb2', '0004_feat_featparam'),
    ]

    operations = [
        migrations.AddField(
            model_name='feat',
            name='fshift_set',
            field=models.ManyToManyField(db_table='feat_fshifts', to='gtdb2.Fshift'),
        ),
    ]
