# Generated by Django 2.1.3 on 2019-01-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtdb2', '0006_cof_feat_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='feat',
            name='origin',
            field=models.CharField(default='annotation', max_length=255),
            preserve_default=False,
        ),
    ]
