# Generated by Django 2.1.3 on 2019-01-14 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtdb2', '0007_feat_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='feat',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gtdb2.Feat'),
        ),
    ]
