# Generated by Django 2.1.3 on 2019-01-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtdb2', '0008_feat_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fshift',
            old_name='type',
            new_name='origin',
        ),
    ]
