# Generated by Django 2.1.3 on 2019-01-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gtdb2', '0010_auto_20190116_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feat',
            name='origin',
            field=models.CharField(choices=[('gbk_annotation', 'GenBank annotation'), ('genetack', 'GeneTack prediction'), ('tblastn', 'tBLASTn prediction')], max_length=255),
        ),
        migrations.AlterField(
            model_name='fshift',
            name='origin',
            field=models.CharField(choices=[('gbk_annotation', 'GenBank annotation'), ('genetack', 'GeneTack prediction'), ('tblastn', 'tBLASTn prediction')], max_length=255),
        ),
    ]
